### ISSUE TITLE
Unknown type `ModalJS` for member `Modal` 

### ISSUE THREAD

**Issue by demirhancosku** [bolav/fuse-modalview#3]
In fuse 0.21.0 when I try to use ModalView, I got this error message;

`Unknown type`ModalJS`for member`Modal`in MainView.`

In my Js;

```
var Modal = require('Modal');
...
var toggleRoute = function(args) {

        Modal.showModal(
                    "This is my title",
                    "This is my body. It can be very long. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sed justo ac arcu semper egestas. Mauris eget ipsum sit amet sem vulputate congue. Nam tellus nunc, malesuada quis dignissim vitae, tincidunt quis mi.",
                    ["Ok", "Cancel"],
                    function (s) {
                        debug_log("Got callback with " + s);
                    });

        if(routeStatus === 'on'){
            routeWill = 'off';
            isRouteOn.value = false;
        }
        else{
            routeWill = 'on';
            isRouteOn.value = true;
        }


        var routeWrite = Storage.writeSync("routeStatus", routeWill);

        //Make a sync http request about starting route

        if(routeWrite){
            routeStatus = routeWill;
        }else{
            isRouteOn.value = ! isRouteOn.value;
        }

        console.log('route durumu: ' + routeStatus);
    };
...
```

In ux;
`
<ModalJS ux:Global="Modal" />
`

Is this related fuse version ?

**Comment by bolav** [comment]
Looks like you are missing the ModalJS.uno in your project.

**Comment by demirhancosku** [comment]
<img width="780" alt="screen shot 2016-07-12 at 23 40 05" src="https://cloud.githubusercontent.com/assets/5027150/16782820/fe37dba2-4889-11e6-929a-279071a5ac61.png">
Actually I've ModalJS.uno and, I've install the package with fusepm. Is there any other things may cause this?

**Comment by demirhancosku** [comment]
I think I found the bug;

When I remove the
```

"Excludes": [
    "fuse_modules/"
  ],
```
in .unoproj, the error was gone. But I think these lines added by fusepm (?)

**Comment by bolav** [comment]
Yes,

The excludes is included, so that the files are not included twice, as they are in a subfolder of the original project. This works good for me. If ModalJS.uno is missing from the build you should get another error than the one you are describing. Can you try to add the excludes back in, and see if the problem returns?
